Make additional stamp files for LLIntAssembly.h per configuration
It seems like changing the build configuration also needs to regenerate
the low level interpreter. If it's not regenerated we receive a linker
error similar to:

```
Undefined symbols for architecture arm64:
  "_llint_entry", referenced from:
      JSC::LLInt::initialize() in libJavaScriptCore.a(UnifiedSource86.o)
     (maybe you meant: _llint_entry_osr_function_for_call_arityCheck, _llint_entry_osr_function_for_construct , _llint_entry_osr , _llint_entry_osr_function_for_construct_arityCheck , _llint_entry_osr_function_for_call )
  "_vmEntryToNative", referenced from:
      JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) in libJavaScriptCore.a(UnifiedSource78.o)
      JSC::Interpreter::executeConstruct(JSC::ExecState*, JSC::JSObject*, JSC::ConstructType, JSC::ConstructData const&, JSC::ArgList const&, JSC::JSValue) in libJavaScriptCore.a(UnifiedSource78.o)
  "_llintPCRangeStart", referenced from:
      JSC::LLInt::isLLIntPC(void*) in libJavaScriptCore.a(UnifiedSource123.o)
  "_sanitizeStackForVMImpl", referenced from:
      JSC::sanitizeStackForVM(JSC::VM*) in libJavaScriptCore.a(UnifiedSource123.o)
  "_vmEntryRecord", referenced from:
      JSC::ExecState::callerFrame(JSC::EntryFrame*&) in libJavaScriptCore.a(UnifiedSource78.o)
      JSC::ExecState::unsafeCallerFrame(JSC::EntryFrame*&) in libJavaScriptCore.a(UnifiedSource78.o)
      JSC::StackVisitor::StackVisitor(JSC::ExecState*, JSC::VM*) in libJavaScriptCore.a(UnifiedSource78.o)
      JSC::UnwindFunctor::copyCalleeSavesToEntryFrameCalleeSavesBuffer(JSC::StackVisitor&) const in libJavaScriptCore.a(UnifiedSource78.o)
      JSC::EntryFrame::vmEntryRecordOffset() in libJavaScriptCore.a(UnifiedSource79.o)
      JSC::DFG::prepareOSREntry(JSC::ExecState*, JSC::CodeBlock*, unsigned int) in libJavaScriptCore.a(UnifiedSource48.o)
      JSC::DFG::restoreCalleeSavesFromVMEntryFrameCalleeSavesBuffer(JSC::Probe::Context&) in libJavaScriptCore.a(UnifiedSource48.o)
      ...
  "_llintPCRangeEnd", referenced from:
      JSC::LLInt::isLLIntPC(void*) in libJavaScriptCore.a(UnifiedSource123.o)
  "_vmEntryToJavaScript", referenced from:
      JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) in libJavaScriptCore.a(UnifiedSource120.o)
      JSC::vmEntryToWasm(void*, JSC::VM*, JSC::ProtoCallFrame*) in libJavaScriptCore.a(UnifiedSource86.o)
ld: symbol(s) not found for architecture arm64
```